name: CI Centos7

on:
  push:
    branches: [master, 'release/**']
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'docs/**'

jobs:
  test_apisix:
    name: run ci on centos7
    runs-on: self-hosted

    services:
      etcd:
        image: gcr.io/etcd-development/etcd:v3.4.0-arm64
        ports:
          - 2379:2379
          - 2380:2380
        env:
          ALLOW_NONE_AUTHENTICATION: yes
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379

    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.4
      with:
        submodules: recursive

    - name: Install Redis Cluster
      run: |
        docker run -d -p ${MASTER1_PORT}:6379 -p ${MASTER2_PORT}:6380 -p ${MASTER3_PORT}:6381 -p ${SLAVE1_PORT}:6382 -p ${SLAVE2_PORT}:6383 -p ${SLAVE3_PORT}:6384 --name redis-cluster yiyiyimu/redis-cluster:latest
      env:
        MASTER1_PORT: 5000
        MASTER2_PORT: 5001
        MASTER3_PORT: 5002
        SLAVE1_PORT: 5003
        SLAVE2_PORT: 5004
        SLAVE3_PORT: 5005

    - name: Running Redis Cluster Test
      run: |
        sudo apt-get install -y redis-tools
        docker ps -a
        redis-cli -h 127.0.0.1 -p 5000 ping
        redis-cli -h 127.0.0.1 -p 5000 cluster nodes

    - name: Running etcd server with TLS
      run: |
        sudo docker run -d -p 12379:12379 -p 12380:12380 \
        -e ALLOW_NONE_AUTHENTICATION=yes \
        -e ETCD_ADVERTISE_CLIENT_URLS=https://0.0.0.0:12379 \
        -e ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:12379 \
        -e ETCD_CERT_FILE=/certs/etcd.pem \
        -e ETCD_KEY_FILE=/certs/etcd.key \
        -e GITHUB_ACTIONS=true \
        -e CI=true \
        -v /home/runner/work/apisix/apisix/t/certs:/certs \
        gcr.io/etcd-development/etcd:v3.4.0-arm64

    - name: Run other docker containers for test
      run: |
        ./ci/install-ext-services-via-docker.sh

    - name: Install dependencies
      run: |
        ./ci/centos7-ci.sh install_dependencies

    - name: Run test cases
      run: |
        ./ci/centos7-ci.sh run_case

