name: Chaos Test

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  chaos-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: setup go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.14"

      - name: Creating minikube cluster
        run: |
          bash ./t/chaos/utils/setup_chaos_utils.sh start_minikube
          wget https://raw.githubusercontent.com/apache/apisix-docker/master/alpine-local/Dockerfile
          mkdir logs
          docker build -t apache/apisix:alpine-local --build-arg APISIX_PATH=. -f Dockerfile .
          minikube cache add apache/apisix:alpine-local -v 7 --alsologtostderr

      - name: Print cluster information
        run: |
          kubectl config view
          kubectl cluster-info
          kubectl get nodes
          kubectl get pods -n kube-system
          kubectl version

      - name: Deploy Etcd with Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install etcd bitnami/etcd --set replicaCount=3
          bash ./t/chaos/utils/setup_chaos_utils.sh ensure_pods_ready app.kubernetes.io/instance=etcd "True True True" 30


      - name: Deploy APISIX
        run: |
          bash ./t/chaos/utils/setup_chaos_utils.sh modify_config
          kubectl create configmap apisix-gw-config.yaml --from-file=./conf/config.yaml
          kubectl apply -f ./kubernetes/deployment.yaml
          kubectl apply -f ./kubernetes/service.yaml
          bash ./t/chaos/utils/setup_chaos_utils.sh ensure_pods_ready app=apisix-gw "True" 30
          kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin.yaml
          bash ./t/chaos/utils/setup_chaos_utils.sh ensure_pods_ready app=httpbin "True" 30
          bash ./t/chaos/utils/setup_chaos_utils.sh port_forward

      - name: Deploy Chaos mesh
        run: |
          curl -sSL https://mirrors.chaos-mesh.org/v1.1.1/install.sh | bash

      - name: run test
        working-directory: ./t/chaos
        run: go test -v -p 1 ./...
