name: Check Markdown links

on: pull_request

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install -g markdown-link-check
    - run: markdown-link-check -q -v '**/*.md'
